title: fabric source
proj_name: notes_fabric_source
description: The Jekyll AsciiDoc Quickstart project is a leg-up in starting your own website hosted on GitHub with content based in AsciiDoc.
permalink: /:categories/:title
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  toc: true
  toclevels: 5
  attributes:
    - proj_name=notes_fabric_source
    - toc=true
    - toclevels=5
    - idseparator=_
    - source-highlighter=prettify
    - icons=font
    - imagesdir=/{proj_name}/images
    - imagesoutdir=/Users/liuhuiyu/AllNotes/{proj_name}/_site/images
categories:
  - name: principle
    showName: 原理
  - name: debug
    showName: 调试
  - name: source
    showName: 源码
  - name: third-lib
    showName: 第三方库
keep_files:
  - images