:title: create channel
:page-navtitle: create channel
:chapter: 2
:section: 4
:page-section: {section}

== create channel

=== 命令 peer channel create

命令如下
[source,bash]
----
peer channel create -c myc -f fabric源码目录下dev-network/config/myc.tx(绝对路径) -o 127.0.0.1:7050 
----

TIP: channel 是 peer 的子命令，create 是 channel 的子命令

create channel 是 peer 节点执行的命令，入口处在 /peer/main.go

./peer/main.go
[source,go]
----
func main() {
	...
	mainCmd.AddCommand(channel.Cmd(nil)) // <1>
	...
}
----
<1> 为 mainCmd 添加了 channel 子命令 

[TIP]
====
mainCmd 就是 *peer*

[source,go]
----
var mainCmd = &cobra.Command{
	Use: "peer"}
----
====

channel 里面什么样呢

./peer/channel/channel.go
[source,go]
----
func Cmd(cf *ChannelCmdFactory) *cobra.Command {
	...
	channelCmd.AddCommand(createCmd(cf)) // <1>
	...
}
----
<1> 添加了 *create* 子命令

createCmd 里面

./peer/channel/create.go
[source,go]
----
func createCmd(cf *ChannelCmdFactory) *cobra.Command {
	createCmd := &cobra.Command{
		Use:   "create",
		Short: "Create a channel",
		Long:  "Create a channel and write the genesis block to a file.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return create(cmd, args, cf) // <1>
		},
	}
	flagList := []string{
		"channelID",
		"file",
		"outputBlock",
		"timeout",
	}
	attachFlags(createCmd, flagList)

	return createCmd
}
----
<1> create channel 实际执行的是 *create* 方法

./peer/channel/create.go
[source,go]
----
func create(cmd *cobra.Command, args []string, cf *ChannelCmdFactory) error {
	...
	if cf == nil {
		cf, err = InitCmdFactory(EndorserNotRequired, PeerDeliverNotRequired, OrdererRequired) // <1>
		...
	}
	return executeCreate(cf)
}
----
<1> 创建了一个 *ChannelCmdFactory* 对象

看一下 *ChannelCmdFactory* 结构 

./peer/channel/channel.go
[source,go]
----
type ChannelCmdFactory struct {
	EndorserClient   pb.EndorserClient
	Signer           msp.SigningIdentity
	BroadcastClient  common.BroadcastClient // <1>
	DeliverClient    deliverClientIntf
	BroadcastFactory BroadcastClientFactory // <2>
}
----
<1> BroadcastClient 用来通信
<2> BroadcastFactory 是一个方法，用来得到 BroadcastClient 对象

./peer/common/broadcastclient.go
[source,go]
----
type BroadcastClient interface { // <1>
	Send(env *cb.Envelope) error
	Close() error
}

type broadcastClient struct { // <2>
	client ab.AtomicBroadcast_BroadcastClient // <3>
}

...

func (s *broadcastClient) Send(env *cb.Envelope) error {
	...
}

func (s *broadcastClient) Close() error {
	...
}
----
<1> BroadcastClient 接口
<2> broadcastClient 实现了 BroadcastClient 接口
<3> 真正完成 Send, Close 动作的是 ab.AtomicBroadcast_BroadcastClient

=== gRPC 的使用

==== AtomicBroadcast

/protos/orderer/ab.proto 文件定义了 AtomicBroadcast 的原型

.protos/orderer/ab.proto
[source,pb]
----
...
service AtomicBroadcast {
    rpc Broadcast(stream common.Envelope) returns (stream BroadcastResponse) {}

    rpc Deliver(stream common.Envelope) returns (stream DeliverResponse) {}
}
----

==== AtomicBroadcastClient

/protos/orderer/ab.proto 经过 gPRC 编译后得到 /protos/orderer/ab.pb.go，里面包括 2 个部分  *AtomicBroadcastClient*，*AtomicBroadcastServer*，这里先看 *AtomicBroadcastClient*

./protos/orderer/ab.pb.go
[source,go]
----
type AtomicBroadcastClient interface { // <1>
	Broadcast(ctx context.Context, opts ...grpc.CallOption) (AtomicBroadcast_BroadcastClient, error)
	Deliver(ctx context.Context, opts ...grpc.CallOption) (AtomicBroadcast_DeliverClient, error)
}

type atomicBroadcastClient struct { // <2>
	cc *grpc.ClientConn
}

func NewAtomicBroadcastClient(cc *grpc.ClientConn) AtomicBroadcastClient { // <3>
	return &atomicBroadcastClient{cc}
}

func (c *atomicBroadcastClient) Broadcast(ctx context.Context, opts ...grpc.CallOption) (AtomicBroadcast_BroadcastClient, error) {
	...
}

type AtomicBroadcast_BroadcastClient interface { // <4>
	Send(*common.Envelope) error
	Recv() (*BroadcastResponse, error)
	grpc.ClientStream
}

type atomicBroadcastBroadcastClient struct { // <5>
	grpc.ClientStream
}

func (x *atomicBroadcastBroadcastClient) Send(m *common.Envelope) error {
	...
}

func (x *atomicBroadcastBroadcastClient) Recv() (*BroadcastResponse, error) {
	...
}
----
<1> AtomicBroadcastClient 接口
<2> atomicBroadcastClient 实现了 AtomicBroadcastClient 接口
<3> 创建一个 atomicBroadcastClient 实例
<4> AtomicBroadcast_BroadcastClient 接口是针对 AtomicBroadcastClient 中的 Broadcast 动作的客户端
<5> atomicBroadcastBroadcastClient 实现了 AtomicBroadcast_BroadcastClient 接口

NOTE: AtomicBroadcast_DeliverClient 也是有的，与 AtomicBroadcast_BroadcastClient 类似，不再缀述 

==== OrdererClient

./peer/common/ordererclient.go
[source,go]
----
type OrdererClient struct { // <1>
	commonClient
}

func NewOrdererClientFromEnv() (*OrdererClient, error) { // <2>
	address, override, clientConfig, err := configFromEnv("orderer") // <3>
	...
}

func (oc *OrdererClient) Broadcast() (ab.AtomicBroadcast_BroadcastClient, error) {
	...
}

func (oc *OrdererClient) Deliver() (ab.AtomicBroadcast_DeliverClient, error) {
	...
}
----
<1> OrdererClient 实现了 AtomicBroadcastClient 接口
<2> NewOrdererClientFromEnv 创建了一 OrdererClient 实例
<3> 获取了关于 orderer 的配置，如地址，超时时间等

前面提到过 InitCmdFactory 方法

./peer/chaincode/common.go
[source,go]
----
func InitCmdFactory(cmdName string, isEndorserRequired, isOrdererRequired bool) (*ChaincodeCmdFactory, error) {
	...
	if isOrdererRequired {
		...
		broadcastClient, err = common.GetBroadcastClientFnc()
		...
	}
	...
}
----

./peer/chaincode/common.go
[source,go]
----
func init() {
	...
	GetBroadcastClientFnc = GetBroadcastClient
	...
}
----

./peer/common/broadcastclient.go
[source,go]
----
func GetBroadcastClient() (BroadcastClient, error) {
	oc, err := NewOrdererClientFromEnv() // <1>
	...
}
----
<1> 调用了 OrdererClient 中的 NewOrdererClientFromEnv 方法


==== 消息的发出

.peer/channel/create.go
[source,go]
----
func sendCreateChainTransaction(cf *ChannelCmdFactory) error {
	...
	defer broadcastClient.Close()
	err = broadcastClient.Send(chCrtEnv) // <1>

	return err
}
----
<1> broadcastClient.Send 方法实际上调用了 gRPC，从 peer 节点发送消息给了 orderer 服务

==== AtomicBroadcastServer

./protos/orderer/ab.pb.go
[source,go]
----
type AtomicBroadcastServer interface {
	Broadcast(AtomicBroadcast_BroadcastServer) error
	Deliver(AtomicBroadcast_DeliverServer) error
}

func RegisterAtomicBroadcastServer(s *grpc.Server, srv AtomicBroadcastServer) { // <1>
	s.RegisterService(&_AtomicBroadcast_serviceDesc, srv)
}

func _AtomicBroadcast_Broadcast_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AtomicBroadcastServer).Broadcast(&atomicBroadcastBroadcastServer{stream}) // <3>
}
...
var _AtomicBroadcast_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orderer.AtomicBroadcast",
	HandlerType: (*AtomicBroadcastServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Broadcast",
			Handler:       _AtomicBroadcast_Broadcast_Handler, <2>
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Deliver",
			Handler:       _AtomicBroadcast_Deliver_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "orderer/ab.proto",
}
----
<1> 注册 server 的方法
<2> 指定 Broadcast 的消息由 _AtomicBroadcast_Broadcast_Handler 方法来处理
<3> 真正处理消息的是 被注册的 server 对象的 Broadcast 方法

./orderer/common/server/main.go
[source,go]
----
func Start(cmd string, conf *localconfig.TopLevel) {
	...
	ab.RegisterAtomicBroadcastServer(grpcServer.Server(), server) // <1>
	...
}
----
<1> 注册了 server

这里的 server 

./orderer/common/server/server.go
[source,go]
----
type server struct { // <1>
	bh    *broadcast.Handler
	dh    *deliver.Handler
	debug *localconfig.Debug
	*multichannel.Registrar
}
...
func (s *server) Broadcast(srv ab.AtomicBroadcast_BroadcastServer) error {
	logger.Debugf("Starting new Broadcast handler")
	defer func() {
		if r := recover(); r != nil {
			logger.Criticalf("Broadcast client triggered panic: %s\n%s", r, debug.Stack())
		}
		logger.Debugf("Closing Broadcast stream")
	}()
	return s.bh.Handle(&broadcastMsgTracer{ // <2>
		AtomicBroadcast_BroadcastServer: srv,
		msgTracer: msgTracer{
			debug:    s.debug,
			function: "Broadcast",
		},
	})
}

// Deliver sends a stream of blocks to a client after ordering
func (s *server) Deliver(srv ab.AtomicBroadcast_DeliverServer) error {
	...
}
----
<1> server 实现了 AtomicBroadcastServer 接口
<2> 实际处理 client 端发出的强求的方法

Handle 方法

./orderer/common/broadcast/broadcast.go
[source,go]
----
func (bh *Handler) Handle(srv ab.AtomicBroadcast_BroadcastServer) error {
	...
	for {
		...
		resp := bh.ProcessMessage(msg, addr) // <1>
		...
	}
}
----
<1> 处理消息

=== solo 

==== 处理消息的方法

./orderer/common/broadcast/broadcast.go
[source,go]
----
func (bh *Handler) ProcessMessage(msg *cb.Envelope, addr string) (resp *ab.BroadcastResponse) {
	...
	if !isConfig {
		...
		err = processor.Order(msg, configSeq)
		...
	} else { // isConfig
		...
		err = processor.Configure(config, configSeq)
		...
	}
	...
}
----

==== processor

processor 实际上是一个 Consenter 接口的实现

./orderer/common/broadcast/broadcast.go
[source,go]
----
type Consenter interface {
	Order(env *cb.Envelope, configSeq uint64) error
	Configure(config *cb.Envelope, configSeq uint64) error
	WaitReady() error
}
----

此处实际工作的是 /orderer/consensus/solo/consensus.go 中的 chain

./orderer/consensus/solo/consensus.go
[source,go]
----
type chain struct { // <1>
	support  consensus.ConsenterSupport
	sendChan chan *message
	exitChan chan struct{}
}
...
func (ch *chain) WaitReady() error {
	return nil
}

func (ch *chain) Order(env *cb.Envelope, configSeq uint64) error {
	select {
	case ch.sendChan <- &message{ // <2>
		configSeq: configSeq,
		normalMsg: env,
	}:
		return nil
	case <-ch.exitChan:
		return fmt.Errorf("Exiting")
	}
}

func (ch *chain) Configure(config *cb.Envelope, configSeq uint64) error {
	select {
	case ch.sendChan <- &message{ // <3>
		configSeq: configSeq,
		configMsg: config,
	}:
		return nil
	case <-ch.exitChan:
		return fmt.Errorf("Exiting")
	}
}
----
<1> chain 实现了 Consenter 接口
<2> Order 方法内部向 sendChan 发消息
<3> Configure 方法内部向 sendChan 发消息

处理消息的是 main 方法

./orderer/consensus/solo/consensus.go
[source,go]
----
func (ch *chain) main() {
	...
	for {
		seq := ch.support.Sequence()
		err = nil
		select {
		case msg := <-ch.sendChan: // <1>
			...
		case <-timer:
			...
		case <-ch.exitChan:
			...
		}
	}
----
<1> sendChan 收到消息时，处理

==== 为什么使用的是 solo 呢

./orderer/common/server/main.go
[source,go]
----
func Start(cmd string, conf *localconfig.TopLevel) {
	...
	manager := initializeMultichannelRegistrar(clusterBootBlock, r, clusterDialer, clusterServerConfig, clusterGRPCServer, conf, signer, metricsProvider, opsSystem, lf, tlsCallback)
	...
}
...
func initializeMultichannelRegistrar(
	bootstrapBlock *cb.Block,
	ri *replicationInitiator,
	clusterDialer *cluster.PredicateDialer,
	srvConf comm.ServerConfig,
	srv *comm.GRPCServer,
	conf *localconfig.TopLevel,
	signer crypto.LocalSigner,
	metricsProvider metrics.Provider,
	healthChecker healthChecker,
	lf blockledger.Factory,
	callbacks ...channelconfig.BundleActor,
) *multichannel.Registrar {
	genesisBlock := extractBootstrapBlock(conf)
	...
	consenters := make(map[string]consensus.Consenter)

	registrar := multichannel.NewRegistrar(lf, signer, metricsProvider, callbacks...)

	consenters["solo"] = solo.New() // <1>
	var kafkaMetrics *kafka.Metrics
	consenters["kafka"], kafkaMetrics = kafka.New(conf.Kafka, metricsProvider, healthChecker) // <2>
	...
	registrar.Initialize(consenters)
	return registrar
}
----
<1> 创建 solo 共识器
<2> 创建 kafka 共识器

./orderer/common/multichannel/registrar.go
[source,go]
----
func (r *Registrar) Initialize(consenters map[string]consensus.Consenter) {
	r.consenters = consenters
	existingChains := r.ledgerFactory.ChainIDs()

	for _, chainID := range existingChains {
		...
		if _, ok := ledgerResources.ConsortiumsConfig(); ok {
			...
			chain := newChainSupport( // <1>
				r,
				ledgerResources,
				r.consenters,
				r.signer,
				r.blockcutterMetrics,
			)
			...
		} else {
			...
		}

	}
	...
}
----
<1> 调用 newChainSupport 方法

./orderer/common/multichannel/chainsupport.go
[source,go]
----
func newChainSupport(
	registrar *Registrar,
	ledgerResources *ledgerResources,
	consenters map[string]consensus.Consenter,
	signer crypto.LocalSigner,
	blockcutterMetrics *blockcutter.Metrics,
) *ChainSupport {
	...
	consenterType := ledgerResources.SharedConfig().ConsensusType() // <1>
	consenter, ok := consenters[consenterType] // <2>
	...
}
----
<1> 获取 共识器 类型，这里实际的值是 solo
<2> 根据 共识器 类型来决定使用哪种共识器
